In [ ]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

file_id = '1tzlAyyIxxlK4G5xX_gbpl6DtkhKAKtZG'
downloaded = drive.CreateFile({'id': file_id})
downloaded.GetContentFile('heart.csv')
!ls -lha covid.csv
!pip install -q xlrd

import pandas as pd
df = pd.read_csv('heart.csv')
df.head()

ls: cannot access 'covid.csv': No such file or directory


age  sex  cp  trtbps  chol  fbs  ...  exng  oldpeak  slp  caa  thall  output
0   63    1   3     145   233    1  ...     0      2.3    0    0      1       1
1   37    1   2     130   250    0  ...     0      3.5    0    0      2       1
2   41    0   1     130   204    0  ...     0      1.4    2    0      2       1
3   56    1   1     120   236    0  ...     0      0.8    2    0      2       1
4   57    0   0     120   354    0  ...     1      0.6    2    0      2       1

[5 rows x 14 columns]

In [ ]:
import sklearn
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn import svm
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
import xgboost as xgb
%matplotlib inline

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [ ]:

y=df.iloc[:,13].values
y=lb.fit_transform(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
x=df.iloc[:,1:13].values
x

array([[  1.,   3., 145., ...,   0.,   0.,   1.],
       [  1.,   2., 130., ...,   0.,   0.,   2.],
       [  0.,   1., 130., ...,   2.,   0.,   2.],
       ...,
       [  1.,   0., 144., ...,   1.,   2.,   3.],
       [  1.,   0., 130., ...,   1.,   1.,   3.],
       [  0.,   1., 130., ...,   1.,   1.,   2.]])

In [ ]:
from sklearn.model_selection import train_test_split   #spliting the data in train set and test set
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:

key = ['LogisticRegression','KNeighborsClassifier','SVC','DecisionTreeClassifier','RandomForestClassifier','GradientBoostingClassifier','AdaBoostClassifier','XGBClassifier']
value = [LogisticRegression(solver='lbfgs',max_iter=350000),KNeighborsClassifier(),SVC(kernel='rbf'),DecisionTreeClassifier(),RandomForestClassifier(),GradientBoostingClassifier(),AdaBoostClassifier(),xgb.XGBClassifier()]
models = dict(zip(key,value))

In [ ]:
for name,algo in models.items():
  model=algo
  model.fit(x_train,y_train)
  y_pred=model.predict(x_test)
  print(name)
  print(confusion_matrix(y_test,y_pred))
  print(accuracy_score(y_test,y_pred))

LogisticRegression
[[24  5]
 [ 4 28]]
0.8524590163934426
KNeighborsClassifier
[[17 12]
 [ 9 23]]
0.6557377049180327
SVC
[[14 15]
 [ 6 26]]
0.6557377049180327
DecisionTreeClassifier
[[21  8]
 [ 8 24]]
0.7377049180327869
RandomForestClassifier
[[25  4]
 [ 6 26]]
0.8360655737704918
GradientBoostingClassifier
[[25  4]
 [ 5 27]]
0.8524590163934426
AdaBoostClassifier
[[25  4]
 [ 5 27]]
0.8524590163934426
XGBClassifier
[[26  3]
 [ 6 26]]
0.8524590163934426
