In [ ]:
import os
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

file_id = '1cfWmaRBcQvHnQRYGmzk2HQ0vumrjFuDf'
downloaded = drive.CreateFile({'id': file_id})
downloaded.GetContentFile('lung cancer dataset.zip')
!ls -lha lung cancer dataset.zip
!pip install -q xlrd

import pandas as pd
df = pd.read_csv('lung cancer dataset.zip')
df

ls: cannot access 'lung': No such file or directory
ls: cannot access 'cancer': No such file or directory
ls: cannot access 'dataset.zip': No such file or directory


GENDER  AGE  SMOKING  ...  SWALLOWING DIFFICULTY  CHEST PAIN  LUNG_CANCER
0        M   69        1  ...                      2           2          YES
1        M   74        2  ...                      2           2          YES
2        F   59        1  ...                      1           2           NO
3        M   63        2  ...                      2           2           NO
4        F   63        1  ...                      1           1           NO
..     ...  ...      ...  ...                    ...         ...          ...
304      F   56        1  ...                      2           1          YES
305      M   70        2  ...                      1           2          YES
306      M   58        2  ...                      1           2          YES
307      M   67        2  ...                      1           2          YES
308      M   62        1  ...                      2           1          YES

[309 rows x 16 columns]

In [ ]:
df.columns

Index(['GENDER', 'AGE', 'SMOKING', 'YELLOW_FINGERS', 'ANXIETY',
       'PEER_PRESSURE', 'CHRONIC DISEASE', 'FATIGUE ', 'ALLERGY ', 'WHEEZING',
       'ALCOHOL CONSUMING', 'COUGHING', 'SHORTNESS OF BREATH',
       'SWALLOWING DIFFICULTY', 'CHEST PAIN', 'LUNG_CANCER'],
      dtype='object')

In [ ]:
df.head()

NameError: ignored

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   AGE                    309 non-null    int64
 1   SMOKING                309 non-null    int64
 2   YELLOW_FINGERS         309 non-null    int64
 3   ANXIETY                309 non-null    int64
 4   PEER_PRESSURE          309 non-null    int64
 5   CHRONIC DISEASE        309 non-null    int64
 6   FATIGUE                309 non-null    int64
 7   ALLERGY                309 non-null    int64
 8   WHEEZING               309 non-null    int64
 9   ALCOHOL CONSUMING      309 non-null    int64
 10  COUGHING               309 non-null    int64
 11  SHORTNESS OF BREATH    309 non-null    int64
 12  SWALLOWING DIFFICULTY  309 non-null    int64
 13  CHEST PAIN             309 non-null    int64
 14  LUNG_CANCER            309 non-null    int64
dtypes: int64(15)
memory usage: 36.3 KB


In [ ]:
all_cols=df.columns
numerical_cols=df._get_numeric_data().columns.to_list()
numerical_cols




['AGE',
 'SMOKING',
 'YELLOW_FINGERS',
 'ANXIETY',
 'PEER_PRESSURE',
 'CHRONIC DISEASE',
 'FATIGUE ',
 'ALLERGY ',
 'WHEEZING',
 'ALCOHOL CONSUMING',
 'COUGHING',
 'SHORTNESS OF BREATH',
 'SWALLOWING DIFFICULTY',
 'CHEST PAIN']

In [ ]:
categorical_cols=list(set(all_cols)-set(numerical_cols))
categorical_cols

['GENDER', 'LUNG_CANCER']

In [ ]:
df.drop(['GENDER'], inplace=True, axis=1)    #dropping the catagorical coloumn

In [ ]:
df

AGE  SMOKING  ...  CHEST PAIN  LUNG_CANCER
0     69        1  ...           2            1
1     74        2  ...           2            1
2     59        1  ...           2            0
3     63        2  ...           2            0
4     63        1  ...           1            0
..   ...      ...  ...         ...          ...
304   56        1  ...           1            1
305   70        2  ...           2            1
306   58        2  ...           2            1
307   67        2  ...           2            1
308   62        1  ...           1            1

[309 rows x 15 columns]

In [ ]:
df.shape

(309, 15)

In [ ]:
#lets work on first few rows
df.head()

AGE  SMOKING  YELLOW_FINGERS  ...  SWALLOWING DIFFICULTY  CHEST PAIN  LUNG_CANCER
0   69        1               2  ...                      2           2          YES
1   74        2               1  ...                      2           2          YES
2   59        1               1  ...                      1           2           NO
3   63        2               2  ...                      2           2           NO
4   63        1               2  ...                      1           1           NO

[5 rows x 15 columns]

In [ ]:
#Pairwise correlation of all columns in the dataframe.
df.corr() #convert all the values so that it will represent b/w -1 and +1


AGE   SMOKING  ...  CHEST PAIN  LUNG_CANCER
AGE                    1.000000 -0.084475  ...   -0.018104     0.089465
SMOKING               -0.084475  1.000000  ...    0.120117     0.058179
YELLOW_FINGERS         0.005205 -0.014585  ...   -0.104829     0.181339
ANXIETY                0.053170  0.160267  ...   -0.113634     0.144947
PEER_PRESSURE          0.018685 -0.042822  ...   -0.094828     0.186388
CHRONIC DISEASE       -0.012642 -0.141522  ...   -0.036938     0.110891
FATIGUE                0.012614 -0.029575  ...   -0.010832     0.150673
ALLERGY                0.027990  0.001913  ...    0.239433     0.327766
WHEEZING               0.055011 -0.129426  ...    0.147640     0.249300
ALCOHOL CONSUMING      0.058985 -0.050623  ...    0.331226     0.288533
COUGHING               0.169950 -0.129471  ...    0.083958     0.248570
SHORTNESS OF BREATH   -0.017513  0.061264  ...    0.024256     0.060738
SWALLOWING DIFFICULTY -0.001270  0.030718  ...    0.069027     0.259730
CHEST PAIN            -0.018104  0.120117  ...    1.000000     0.190451
LUNG_CANCER            0.089465  0.058179  ...    0.190451     1.000000

[15 rows x 15 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()


In [ ]:

y=df.iloc[:,14].values
y=lb.fit_transform(y)
y

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [ ]:
x=df.iloc[:,1:14].values
x

array([[1, 2, 2, ..., 2, 2, 2],
       [2, 1, 1, ..., 2, 2, 2],
       [1, 1, 1, ..., 2, 1, 2],
       ...,
       [2, 1, 1, ..., 1, 1, 2],
       [2, 1, 2, ..., 2, 1, 2],
       [1, 1, 1, ..., 1, 2, 1]])

In [ ]:
from sklearn.model_selection import train_test_split   #spliting the data in train set and test set
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
df_train.shape,df_test.shape

((247, 15), (62, 15))

In [ ]:
import sklearn
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn import svm
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
%matplotlib inline

In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(solver='lbfgs',max_iter=10000)
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
y_pred

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[ 7,  1],
       [ 2, 52]])

In [ ]:
#prediction accuracy 95%

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf=RandomForestClassifier(n_estimators=3,criterion='entropy')
classifier_rf.fit(x_train,y_train)
y_pred=classifier_rf.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[ 7,  1],
       [ 2, 52]])

In [ ]:
#prediction accuracy 95%

In [ ]:

from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier() #neigh => model
neigh.fit(x_train, y_train) #training the data
predictions = neigh.predict(x_test)   #X-test ---> Y_test

In [ ]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.88      0.88      0.88         8
           1       0.98      0.98      0.98        54

    accuracy                           0.97        62
   macro avg       0.93      0.93      0.93        62
weighted avg       0.97      0.97      0.97        62



In [ ]:
# Confusion Matrix
confusion_matrix(y_test,predictions)

array([[ 7,  1],
       [ 1, 53]])

In [ ]:
#prediction 96.7%

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtr = DecisionTreeClassifier(random_state=0)
dtr.fit(x_train, y_train)
predictions = dtr.predict(x_test)


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.67      1.00      0.80         8
           1       1.00      0.93      0.96        54

    accuracy                           0.94        62
   macro avg       0.83      0.96      0.88        62
weighted avg       0.96      0.94      0.94        62



In [ ]:
confusion_matrix(y_test,predictions)

array([[ 8,  0],
       [ 4, 50]])

In [ ]:
#prediction accuracy 94%