In [1]:
import pandas as pd
df=pd.read_csv('C:/Users/Dell/Downloads/Prostate_Cancer.csv')
df.head()

id diagnosis_result  radius  texture  perimeter  area  smoothness  \
0   1                M      23       12        151   954       0.143   
1   2                B       9       13        133  1326       0.143   
2   3                M      21       27        130  1203       0.125   
3   4                M      14       16         78   386       0.070   
4   5                M       9       19        135  1297       0.141   

   compactness  symmetry  fractal_dimension  
0        0.278     0.242              0.079  
1        0.079     0.181              0.057  
2        0.160     0.207              0.060  
3        0.284     0.260              0.097  
4        0.133     0.181              0.059

In [2]:
y=df.iloc[:,1].values
y

array(['M', 'B', 'M', 'M', 'M', 'B', 'M', 'M', 'M', 'M', 'M', 'M', 'B',
       'M', 'M', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M',
       'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'B', 'M',
       'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M', 'M', 'B', 'B', 'B',
       'M', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'M'], dtype=object)

In [3]:
import sklearn
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn import svm
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
%matplotlib inline

In [4]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y=lb.fit_transform(y)
y

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [5]:
x=df.iloc[:,2:10].values
x

array([[2.300e+01, 1.200e+01, 1.510e+02, 9.540e+02, 1.430e-01, 2.780e-01,
        2.420e-01, 7.900e-02],
       [9.000e+00, 1.300e+01, 1.330e+02, 1.326e+03, 1.430e-01, 7.900e-02,
        1.810e-01, 5.700e-02],
       [2.100e+01, 2.700e+01, 1.300e+02, 1.203e+03, 1.250e-01, 1.600e-01,
        2.070e-01, 6.000e-02],
       [1.400e+01, 1.600e+01, 7.800e+01, 3.860e+02, 7.000e-02, 2.840e-01,
        2.600e-01, 9.700e-02],
       [9.000e+00, 1.900e+01, 1.350e+02, 1.297e+03, 1.410e-01, 1.330e-01,
        1.810e-01, 5.900e-02],
       [2.500e+01, 2.500e+01, 8.300e+01, 4.770e+02, 1.280e-01, 1.700e-01,
        2.090e-01, 7.600e-02],
       [1.600e+01, 2.600e+01, 1.200e+02, 1.040e+03, 9.500e-02, 1.090e-01,
        1.790e-01, 5.700e-02],
       [1.500e+01, 1.800e+01, 9.000e+01, 5.780e+02, 1.190e-01, 1.650e-01,
        2.200e-01, 7.500e-02],
       [1.900e+01, 2.400e+01, 8.800e+01, 5.200e+02, 1.270e-01, 1.930e-01,
        2.350e-01, 7.400e-02],
       [2.500e+01, 1.100e+01, 8.400e+01, 4.760e+02, 1.1

In [6]:
x.shape

(100, 8)

In [7]:
y.shape

(100,)

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [9]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression(solver='lbfgs',max_iter=10000)
lg.fit(x_train,y_train)
y_pred=lg.predict(x_test)
y_pred

array([0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1])

In [10]:
y_test

array([0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1])

In [11]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[ 5,  1],
       [ 4, 10]], dtype=int64)

In [12]:
#80 percent accuracy

In [13]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf=RandomForestClassifier(n_estimators=8,criterion='entropy')
classifier_rf.fit(x_train,y_train)
y_pred=classifier_rf.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[ 5,  1],
       [ 4, 10]], dtype=int64)

In [14]:
#80 percent

In [15]:
from sklearn.svm import SVC
classifier_svm_linear=SVC(kernel='linear')
classifier_svm_linear.fit(x_train,y_train)
y_pred=classifier_svm_linear.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[ 5,  1],
       [ 4, 10]], dtype=int64)

In [16]:
#70 accuracy

In [17]:
#input=([[]])
#from sklearn.linear_model import LogisticRegression
#lg=LogisticRegression(solver='lbfgs',max_iter=10000)
#lg.fit(x_train,y_train)
#y_prein=lg.predict(input)
#y_prein

In [18]:
from sklearn.tree import DecisionTreeClassifier
dtr = DecisionTreeClassifier(random_state=0)
dtr.fit(x_train, y_train)
y_pred = dtr.predict(x_test)
confusion_matrix(y_test,y_pred)


array([[6, 0],
       [5, 9]], dtype=int64)

In [19]:
#80 percent