In [ ]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

file_id = '1lSM3_0Ccxv6Ul5L1FPQeGucItI3mjJ3w'
downloaded = drive.CreateFile({'id': file_id})
downloaded.GetContentFile('tumor.csv')
!ls -lha tumor.csv
!pip install -q xlrd

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

import pandas as pd
df = pd.read_csv('tumor.csv')
df

-rw-r--r-- 1 root root 43K Jun  3 16:37 tumor.csv


diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0           M       17.300  ...          0.3138                  0.08113
1           B       10.800  ...          0.2965                  0.07662
2           B       10.260  ...          0.2937                  0.07722
3           B       11.130  ...          0.2383                  0.07083
4           B       10.180  ...          0.3055                  0.08797
..        ...          ...  ...             ...                      ...
164         B       11.410  ...          0.1811                  0.07427
165         B        9.567  ...          0.2757                  0.08178
166         M       21.710  ...          0.2510                  0.06494
167         B       11.740  ...          0.3101                  0.06688
168         M       15.530  ...          0.3512                  0.12040

[169 rows x 31 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                169 non-null    object 
 1   radius_mean              169 non-null    float64
 2   texture_mean             169 non-null    float64
 3   perimeter_mean           169 non-null    float64
 4   area_mean                169 non-null    float64
 5   smoothness_mean          169 non-null    float64
 6   compactness_mean         169 non-null    float64
 7   concavity_mean           169 non-null    float64
 8   concave points_mean      169 non-null    float64
 9   symmetry_mean            169 non-null    float64
 10  fractal_dimension_mean   169 non-null    float64
 11  radius_se                169 non-null    float64
 12  texture_se               169 non-null    float64
 13  perimeter_se             169 non-null    float64
 14  area_se                  1

In [ ]:
y=df.iloc[:,0].values
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y=lb.fit_transform(y)
y

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1])

In [ ]:
from 

In [ ]:
x=df.iloc[:,1:].values
x

array([[1.730e+01, 1.708e+01, 1.130e+02, ..., 1.857e-01, 3.138e-01,
        8.113e-02],
       [1.080e+01, 2.198e+01, 6.879e+01, ..., 7.485e-02, 2.965e-01,
        7.662e-02],
       [1.026e+01, 1.222e+01, 6.575e+01, ..., 6.696e-02, 2.937e-01,
        7.722e-02],
       ...,
       [2.171e+01, 1.725e+01, 1.409e+02, ..., 1.820e-01, 2.510e-01,
        6.494e-02],
       [1.174e+01, 1.402e+01, 7.424e+01, ..., 8.290e-02, 3.101e-01,
        6.688e-02],
       [1.553e+01, 3.356e+01, 1.037e+02, ..., 2.014e-01, 3.512e-01,
        1.204e-01]])

In [ ]:
import sklearn
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn import svm
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
import xgboost as xgb
%matplotlib inline

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
key = ['LogisticRegression','KNeighborsClassifier','SVC','DecisionTreeClassifier','RandomForestClassifier','GradientBoostingClassifier','AdaBoostClassifier','XGBClassifier']
value = [LogisticRegression(solver='lbfgs',max_iter=10000),KNeighborsClassifier(),SVC(kernel='rbf'),DecisionTreeClassifier(),RandomForestClassifier(),GradientBoostingClassifier(),AdaBoostClassifier(),xgb.XGBClassifier()]
models = dict(zip(key,value))

NameError: ignored

In [ ]:
for name,algo in models.items():
  model=algo
  model.fit(x_train,y_train)
  y_pred=model.predict(x_test)
  print(name)
  print(confusion_matrix(y_test,y_pred))
  print(accuracy_score(y_test,y_pred))



LogisticRegression
[[21  2]
 [ 2  9]]
0.8823529411764706
KNeighborsClassifier
[[23  0]
 [ 4  7]]
0.8823529411764706
SVC
[[23  0]
 [ 4  7]]
0.8823529411764706
DecisionTreeClassifier
[[23  0]
 [ 1 10]]
0.9705882352941176
RandomForestClassifier
[[22  1]
 [ 1 10]]
0.9411764705882353
GradientBoostingClassifier
[[23  0]
 [ 1 10]]
0.9705882352941176
AdaBoostClassifier
[[23  0]
 [ 1 10]]
0.9705882352941176
XGBClassifier
[[23  0]
 [ 1 10]]
0.9705882352941176
